version: "3"

services:
  xtlab-mssql:
    image: "mcr.microsoft.com/azure-sql-edge"
    container_name: mssqlserver # tên container
    environment:
      SA_PASSWORD: Admin@123 #Thiết lập password
      ACCEPT_EULA: Y
      MSSQL_USER: SA
      MSSQL_PID: Developer
    volumes:
      - ./mssqlvolume:/var/opt/mssql/data # thư mục lưu DB
      # - ./bk:/var/opt/mssql/backup # thư  mục chứa file backup
    ports:
      - "1433:1433" # cổng kết nối

volumes:
  mssqlvolume:
